steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Clone terraform-lab-foundation'
  entrypoint: git
  args: ['clone', 'https://github.com/CloudVLab/terraform-lab-foundation.git']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Rsync terraform-lab-foundation/basics'
  args: ['gcloud', 'storage', 'rsync', '--delete-unmatched-destination-objects', '--recursive', 'terraform-lab-foundation/basics', 'gs://terraform-lab-foundation/basics']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Rsync terraform-lab-foundation/solutions'
  args: ['gcloud', 'storage', 'rsync', '--delete-unmatched-destination-objects', '--recursive', 'terraform-lab-foundation/solutions', 'gs://terraform-lab-foundation/solutions']
