steps:
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['init']
  id: init-terraform
  dir: '${_TERRAFORM_DIR}' 
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['validate']
  id: validate-terraform
  dir: '${_TERRAFORM_DIR}' 
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['apply', '-auto-approve']
  id: apply-terraform
  dir: '${_TERRAFORM_DIR}' 
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['destroy', '-auto-approve']
  id: destroy-terraform
  dir: '${_TERRAFORM_DIR}' 
substitutions:  
  _PROVIDER_VER: 1.12.1
  _TERRAFORM_DIR: solutions/gen_ai_models/stable
tags: ['terraform-lab-foundation', 'gen-ai', 'models']
