steps:
# Terraform Test Suite
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['init']
  id: init-terraform
  dir: '${_TERRAFORM_DIR}' 
- name: 'hashicorp/terraform:${_PROVIDER_VER}'
  args: ['validate']
  id: validate-terraform
  dir: '${_TERRAFORM_DIR}' 
# Remove additional steps - only validate Terraform
#  - name: 'hashicorp/terraform:${_PROVIDER_VER}'
#    args: ['apply', '-var-file=test.tfvars', '-auto-approve']
#    id: apply-terraform
#    dir: '${_TERRAFORM_DIR}' 
#  - name: 'hashicorp/terraform:${_PROVIDER_VER}'
#    args: ['destroy', '-var-file=test.tfvars', '-auto-approve']
#    id: destroy-terraform
#    dir: '${_TERRAFORM_DIR}' 
substitutions:  
  _PROVIDER_VER: 1.0.1
  _TERRAFORM_DIR: solutions/set_persona/stable
tags: ['terraform-lab-foundation','chatbot', 'persona']  
